binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 1000
error_on_line_overflow = true
error_on_unformatted = false
fn_args_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
hard_tabs = false
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
license_template_path = ""
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Crate"
newline_style = "Auto"
# When I comment out blocks of code using multiline comments I don't want
# rustfmt to change them to EOL comments.
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = false
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
# required_version
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 1000
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
version = "One"
where_single_line = false
wrap_comments = true
